/-!
# Domain-Specific Examples Gallery

Real-world domain examples showcasing how LeanHypothesis can be used
for testing domain-specific properties in various application areas.
-/

import LeanHypothesis.Syntax

open LeanHypothesis.Syntax

-- Example 1: Web Application Data

structure URL where
  scheme : String
  host : String  
  port : Option Nat
  path : String
  query : List (String × String)

def URL.isValid (url : URL) : Bool :=
  url.scheme ∈ ["http", "https"] ∧ 
  url.host.length > 0 ∧
  (url.port.map (· > 0 ∧ · ≤ 65535)).getD true

-- Strategy for generating valid URLs
strategy ValidURL : URL := fun s => do
  -- Parse URL structure generated by Hypothesis with web-specific constraints
  sorry

property urlValidityPreserved : URL where
  ∀hypothesis (url : URL), url.isValid → url.isValid

structure HTTPRequest where
  method : String
  url : URL
  headers : List (String × String)
  body : Option String

property httpMethodValid : HTTPRequest where
  ∀hypothesis (req : HTTPRequest), 
    req.method ∈ ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"]

-- Example 2: Financial Domain

structure Money where
  amount : ℚ
  currency : String

def Money.add (m1 m2 : Money) : Option Money :=
  if m1.currency = m2.currency then
    some ⟨m1.amount + m2.amount, m1.currency⟩
  else none

structure Transaction where
  id : String
  from_account : String
  to_account : String
  amount : Money
  timestamp : Nat
  description : String

def Transaction.isValid (tx : Transaction) : Bool :=
  tx.amount.amount > 0 ∧ 
  tx.from_account ≠ tx.to_account ∧
  tx.id.length > 0

-- Strategy for realistic financial data
strategy RealisticTransaction : Transaction := fun s => do
  -- Generate realistic transaction data with proper constraints
  sorry

property transactionAmountPositive : Transaction where
  ∀hypothesis (tx : Transaction), tx.isValid → tx.amount.amount > 0

property moneySameCurrencyAddition : Money where
  ∀hypothesis (m1 m2 : Money), 
    m1.currency = m2.currency → 
    ∃ result, m1.add m2 = some result ∧ result.currency = m1.currency

-- Example 3: Gaming Domain

structure Player where
  id : String
  name : String
  level : Nat
  experience : Nat
  health : Nat
  maxHealth : Nat
  inventory : List String

def Player.isAlive (p : Player) : Bool := p.health > 0

def Player.levelUp (p : Player) : Player :=
  if p.experience ≥ p.level * 100 then
    { p with 
      level := p.level + 1, 
      maxHealth := p.maxHealth + 10,
      health := min (p.health + 5) (p.maxHealth + 10) }
  else p

-- Strategy for valid player states
strategy ValidPlayer : Player := fun s => do
  -- Generate realistic player data with gaming constraints
  sorry

property playerHealthNonNegative : Player where
  ∀hypothesis (p : Player), p.health ≤ p.maxHealth

property levelUpPreservesInvariants : Player where
  ∀hypothesis (p : Player),
    let p' := p.levelUp
    p'.health ≤ p'.maxHealth ∧ p'.level ≥ p.level

structure GameState where
  players : List Player
  currentTurn : Nat
  gamePhase : String
  winner : Option String

property gameStateConsistent : GameState where
  ∀hypothesis (state : GameState),
    state.currentTurn < state.players.length ∧
    (state.winner.isSome → state.gamePhase = "ended")

-- Example 4: Data Science/ML Domain

structure Dataset where
  features : List (List ℚ)
  labels : List String
  metadata : List (String × String)

def Dataset.isValid (ds : Dataset) : Bool :=
  ds.features.length = ds.labels.length ∧
  ds.features.all (fun row => row.length = (ds.features.head?.map List.length).getD 0)

-- Strategy for well-formed datasets
strategy WellFormedDataset : Dataset := fun s => do
  -- Generate realistic ML dataset with proper dimensionality
  sorry

property datasetDimensionsConsistent : Dataset where
  ∀hypothesis (ds : Dataset), ds.isValid → 
    ds.features.all (fun row => row.length = (ds.features.head?.map List.length).getD 0)

structure Model where
  weights : List ℚ
  bias : ℚ
  activationFunction : String

def Model.predict (model : Model) (input : List ℚ) : ℚ :=
  if input.length = model.weights.length then
    model.bias + (List.zip input model.weights).map (fun (x, w) => x * w) |>.sum
  else 0

property modelPredictionDeterministic : Model where
  ∀hypothesis (model : Model) (input : List ℚ),
    model.predict input = model.predict input

-- Example 5: Compiler/Programming Language Domain

inductive AST where
  | literal : ℚ → AST
  | variable : String → AST  
  | binaryOp : String → AST → AST → AST
  | unaryOp : String → AST → AST
  | letBinding : String → AST → AST → AST

def AST.freeVariables : AST → List String
  | literal _ => []
  | variable x => [x]
  | binaryOp _ e1 e2 => e1.freeVariables ++ e2.freeVariables
  | unaryOp _ e => e.freeVariables
  | letBinding x e1 e2 => e1.freeVariables ++ (e2.freeVariables.filter (· ≠ x))

-- Strategy for generating valid ASTs
strategy ValidAST : AST := fun s => do
  -- Generate realistic AST structures with proper variable scoping
  sorry

property astSubstitutionPreservesFreeVars : AST where
  ∀hypothesis (ast : AST) (var : String) (replacement : AST),
    let substituted := sorry -- substitute var with replacement in ast
    (var ∉ ast.freeVariables) → substituted = ast

-- Example 6: Distributed Systems Domain

structure NodeId where
  id : Nat

structure Message where
  from : NodeId
  to : NodeId
  content : String
  timestamp : Nat

structure ClusterState where
  nodes : List NodeId
  messages : List Message
  leader : Option NodeId

def ClusterState.isConsistent (state : ClusterState) : Bool :=
  -- At most one leader
  state.leader.map (fun leader => leader ∈ state.nodes) |>.getD true ∧
  -- All messages reference valid nodes
  state.messages.all (fun msg => msg.from ∈ state.nodes ∧ msg.to ∈ state.nodes)

-- Strategy for consistent cluster states
strategy ConsistentCluster : ClusterState := fun s => do
  -- Generate realistic distributed system states
  sorry

property clusterConsistencyMaintained : ClusterState where
  ∀hypothesis (state : ClusterState), state.isConsistent

-- Test runners for domain examples

def runWebDomainTests : IO Unit := do
  IO.println "🌐 Testing Web Application Properties"
  IO.println "=" * 40
  
  IO.print "URL validity preserved... "
  let result1 ← urlValidityPreservedTest
  IO.println (if result1 then "✓ PASS" else "✗ FAIL")
  
  IO.print "HTTP method validity... "
  let result2 ← httpMethodValidTest
  IO.println (if result2 then "✓ PASS" else "✗ FAIL")

def runFinancialDomainTests : IO Unit := do
  IO.println "\n💰 Testing Financial Domain Properties"
  IO.println "=" * 42
  
  IO.print "Transaction amount positive... "
  let result1 ← transactionAmountPositiveTest
  IO.println (if result1 then "✓ PASS" else "✗ FAIL")
  
  IO.print "Money same currency addition... "
  let result2 ← moneySameCurrencyAdditionTest
  IO.println (if result2 then "✓ PASS" else "✗ FAIL")

def runGamingDomainTests : IO Unit := do
  IO.println "\n🎮 Testing Gaming Domain Properties"
  IO.println "=" * 37
  
  IO.print "Player health non-negative... "
  let result1 ← playerHealthNonNegativeTest
  IO.println (if result1 then "✓ PASS" else "✗ FAIL")
  
  IO.print "Level up preserves invariants... "
  let result2 ← levelUpPreservesInvariantsTest
  IO.println (if result2 then "✓ PASS" else "✗ FAIL")
  
  IO.print "Game state consistency... "
  let result3 ← gameStateConsistentTest
  IO.println (if result3 then "✓ PASS" else "✗ FAIL")

def runDataScienceDomainTests : IO Unit := do
  IO.println "\n📊 Testing Data Science Domain Properties"
  IO.println "=" * 45
  
  IO.print "Dataset dimensions consistent... "
  let result1 ← datasetDimensionsConsistentTest
  IO.println (if result1 then "✓ PASS" else "✗ FAIL")
  
  IO.print "Model prediction deterministic... "
  let result2 ← modelPredictionDeterministicTest
  IO.println (if result2 then "✓ PASS" else "✗ FAIL")

def runCompilerDomainTests : IO Unit := do
  IO.println "\n🔧 Testing Compiler Domain Properties"
  IO.println "=" * 40
  
  IO.print "AST substitution preserves free vars... "
  let result1 ← astSubstitutionPreservesFreeVarsTest
  IO.println (if result1 then "✓ PASS" else "✗ FAIL")

def runDistributedSystemsTests : IO Unit := do
  IO.println "\n🌍 Testing Distributed Systems Properties"
  IO.println "=" * 45
  
  IO.print "Cluster consistency maintained... "
  let result1 ← clusterConsistencyMaintainedTest
  IO.println (if result1 then "✓ PASS" else "✗ FAIL")

-- Main domain examples test runner
def runDomainTests : IO Unit := do
  IO.println "🚀 LeanHypothesis Domain-Specific Examples Gallery"
  IO.println "=" * 60
  IO.println "Testing real-world domain properties with sophisticated constraints\n"
  
  runWebDomainTests
  runFinancialDomainTests
  runGamingDomainTests
  runDataScienceDomainTests
  runCompilerDomainTests
  runDistributedSystemsTests
  
  IO.println "\n✅ All domain-specific property tests completed!"
  IO.println "\nDomain examples demonstrated:"
  IO.println "• Web application data (URLs, HTTP requests)"
  IO.println "• Financial systems (money, transactions)"
  IO.println "• Gaming applications (players, game states)"
  IO.println "• Data science/ML (datasets, models)"
  IO.println "• Compiler design (ASTs, variable scoping)"
  IO.println "• Distributed systems (clusters, consensus)"
  IO.println "• Complex domain constraints and invariants"
  IO.println "• Real-world data generation patterns"

#eval runDomainTests
